### ISSUE TITLE
Duplicate name

### ISSUE THREAD

**Issue by ajsb85** [quorrajs/Positron#1]
Positron is the new project of @Mozilla for Run App with Gecko and Spidermonkey

**Comment by 0xnbk** [comment]
Hi @ajsb85 Thanks for notifying this. We where not aware of it! Considering our project QuorraJS (Just another NodeJS MVC Framework), Positron is like a kernel & is always a part of QuorraJS. There is no chance in shipping it as a separate library/product. Does this really matter or do we have to change the name? We believe, we are not violating any TradeMarks/Copyrights.

Thanks,
NBK
